### PR TITLE
⬆️ Upgrades UniFi Network Application to 7.0.25

### PR DESCRIPTION
**Pull request by rsnodgrass**
* update to Network Application 7.0.25
https://community.ui.com/releases/UniFi-Network-Application-7-0-25/3344c362-7da5-4ecd-a403-3b47520e3c01

# Proposed Changes

> (Describe the changes and rationale behind them)

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Comment by adamfeldman** [comment]
@frenck is this PR missing anything that is required? I peeked and was surprised to see no [Checks](https://github.com/hassio-addons/addon-unifi/pull/354/checks) ran, unlike when I did #328 a few months ago. Thank you!

**Comment by tornenen** [comment]
Any news on this? Need this Version to Migrate from my standalone one.

**Review by olex0r — COMMENTED** [review]
Minor version change of deb package

**Comment by olex0r** [comment]
joining the waiting

**Pull request merged**
