### PR TITLE
⬆️ Upgrades UniFi Network Application to 7.2.92

### PR DESCRIPTION
**Pull request by hip4**
# Proposed Changes

update to latest stable version 7.2.92
See more info about release here:
https://community.ui.com/releases/UniFi-Network-Application-7-2-92/f1903cbc-4daa-4695-ac8c-7324bcff529a
or
https://www.reddit.com/r/UNIFI/comments/wj49lt/unifi_network_application_7292/

### CODE REVIEW

**Comment by rsnodgrass** [comment]
Thank you @hip4 and @frenck!

**Comment by frenck** [comment]
Thanks, but please avoid the pinging, it's another notification in my inbox unneeded. Thanks 👍

**Review by rsnodgrass — COMMENTED** [review]
Correct official release 7.2.92 version URL.

**Comment by numero-trey** [comment]
Is there something blocking this merge? This is a big release because it finally adds local DNS entries!

**Comment by rsnodgrass** [comment]
> Is there something blocking this merge? This is a big release because it finally adds local DNS entries!

Ideally, there would be a process to expedite releases or allow multiple parties to be able to review/publish. If this had significant security patches, this delay would be a huge issue. IMO, there should also be a path for being able to have Release Candidates/Betas available to those who want them.

**Comment by frenck** [comment]
>  If this had significant security patches, this delay would be a huge issue. 

Just that is taken care of, however this is not the case now, so no need to rush or prioritize this right now.

**Comment by frenck** [comment]
> Is there something blocking this merge? This is a big release because it finally adds local DNS entries!

It awaits time allocation for review and testing across a bunch of device ensure it works. Please have patience.

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Thanks, @hip4 👍

**Comment by frenck** [comment]
Just a small heads up on the reasoning that I haven't shipped this yet at this point: One of the systems I use for testing shows a data migration issue using the edge build. I'm not sure if this is a one-off issue or a structural issue. Looking into it.

**Pull request merged**
