### PR TITLE
⬆️ Upgrades UniFi Network Application to 7.3.83

### PR DESCRIPTION
**Pull request by hip4**
# Proposed Changes

> update unifi to version 7.3.83

## Related Documentation

> https://community.ui.com/releases/UniFi-Network-Application-7-3-83/88f5ff3f-4c13-45e2-b57e-ad04b4140528

### CODE REVIEW

**Comment by hip4** [comment]
Can you please review the pr or give me feedback what I need to change?

**Review by JonathanVarild — COMMENTED** [review]
Been running [my own fork](https://github.com/JonathanVarild/addon-unifi) based on this pull request for multiple days now without any issues. Seems to be working perfectly and without crashes or any other unexpected behaviour.

**Comment by domhaas** [comment]
@frenck yould you please add a label to the pull-request that the pipeline proceeds? Thx!

**Comment by frenck** [comment]
Thanks, @hip4 👍

**Pull request merged**
