### PR TITLE
Update unifi controller to 5.13.32

### PR DESCRIPTION
**Pull request by allanpersson**
Release notes: https://community.ui.com/releases/UniFi-Network-Controller-5-13-32/85eee834-c987-4875-8de2-51c6842d7bd3

DL url confirmed working

# Proposed Changes

> (Describe the changes and rationale behind them)

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

<blockquote><div> Ubiquiti Community</div><div><strong><a href="http://community.ui.com/releases/UniFi-Network-Controller-5-13-32/85eee834-c987-4875-8de2-51c6842d7bd3">5.13.32 | Ubiquiti Community</a></strong></div></blockquote>

### CODE REVIEW

**Comment by frenck** [comment]
@allanpersson This build was broken and thus an incomplete PR.

Please next time, test before opening a PR. I will not accept any PRs from you again without proof of testing and working case.

**Comment by allanpersson** [comment]
> @allanpersson This build was broken and thus an incomplete PR.
> 
> Please next time, test before opening a PR. I will not accept any PRs from you again without proof of testing and working case.

I'm sorry to hear, the DL url in docker file was working when I submitted the PR 🙏

I'll try to learn how to do the testing part

**Comment by frenck** [comment]
Just check out a clone of this repository in the `/addons` folder of your installation. It will show up as a local add-on. Hitting install would build it from the source.

**Comment by allanpersson** [comment]
> Just check out a clone of this repository in the `/addons` folder of your installation. It will show up as a local add-on. Hitting install would build it from the source.

Thanks for the advice I will try it out 🙏
And sorry for the inconvenience, I only checked the DL url 🙈

**Pull request merged**
