### PR TITLE
⬆️ Upgrades UniFi Network Application to 7.4.162

### PR DESCRIPTION
**Pull request by anthonyangel**
# Proposed Changes

Update the Unifi Network Application to the latest version, see the release notes [here](https://community.ui.com/releases/UniFi-Network-Application-7-4-156/15ac6260-9cd1-4ac3-a91c-4880c1c87882)

### CODE REVIEW

**Review by cwmoriarty — COMMENTED** [review]
lgtm

**Comment by anthonyangel** [comment]
@frenck @cwmoriarty the build is failing on this, as some other dependencies need bumping. Would you prefer them in this PR, or a separate PR to go in first for just the deps?

**Comment by cwmoriarty** [comment]
> @frenck @cwmoriarty the build is failing on this, as some other dependencies need bumping. Would you prefer them in this PR, or a separate PR to go in first for just the deps?

If I understand correctly @frenck had some apprehensions about fixing the dependencies in a single PR... Not sure tho. 
https://github.com/hassio-addons/addon-unifi/pull/433/commits/fdd4caea1cde089393a6ff3679476428bfb85d63#r1241246503

**Comment by frenck** [comment]
Rebased the PR after upgrading the base dependencies in other PRs.

**Comment by frenck** [comment]
Adjusted PR to upgrade to 7.4.162

Ref: https://community.ui.com/releases/UniFi-Network-Application-7-4-162/50b4b930-631e-4ada-87c4-0b4ea5fb26a7

**Review by frenck — APPROVED** [review]
Thanks, @anthonyangel 👍 

../Frenck

**Pull request merged**
