### PR TITLE
Upgrades UniFi Network Application to 8.4.59

### PR DESCRIPTION
**Pull request by dobrac**
# Proposed Changes

Updated the Unifi package in the Dockerfile to version 8.4.59

Rel notes: https://community.ui.com/releases/UniFi-Network-Application-8-4-59/d3ba4443-ad36-4566-b1e6-2d21d8b4f225?page=5

## Summary by CodeRabbit

- **New Features**
	- Upgraded the Unifi application to version 8.4.59, which may include enhancements, bug fixes, or new features.
  
- **Chores**
	- Updated the download URL in the Dockerfile for the Unifi package.

### CODE REVIEW

**Comment by dobrac** [comment]
Here is a link to the security bulletin, which this update should fix, too:
https://community.ui.com/releases/Security-Advisory-Bulletin-042-042/c4f68b56-cdc4-4128-b2cb-5870209d1704

**Comment by rami-v** [comment]
Hi
How can i update the UniFi Network Application add-on - on home assistant OS
i get an update in the web ui that is give me download ling to deb file

in HAOS the docker system is blocked and cannot access to run the update
what is the way to update this?

thanks.

**Comment by renewoensdregt** [comment]
You have to wait until the pull request is incorporated by Frenck.
________________________________

**Comment by rami-v** [comment]
Thanks
I will wait…
Rami Vaitzman.
Project Manager.
O.M.C Group.
0542300790.

‫ב-8 בספט׳ 2024, בשעה 14:09, ‏‏renewoensdregt ***@***.***> כתב/ה:‬

﻿

You have to wait until the pull request is incorporated by Frenck.
________________________________

**Pull request closed without merging**
