### PR TITLE
Upgrade to 7.3.76 unifi network app

### PR DESCRIPTION
**Pull request by kilkenny44**
# Proposed Changes

> Just an upgrade to 7.3.76 unifi network app

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Comment by kilkenny44** [comment]
missed label

**Comment by pattyland** [comment]
According to [the release thread](https://community.ui.com/releases/UniFi-Network-Application-7-3-76/85c75fc7-3e0f-4e99-aa90-7068af4f1141) (whose link is missing here):
> Please note that Java 11 is required

This requirement does not seem fulfilled. Did you test it with Java 8?

**Comment by kilkenny44** [comment]
> According to [the release thread](https://community.ui.com/releases/UniFi-Network-Application-7-3-76/85c75fc7-3e0f-4e99-aa90-7068af4f1141) (whose link is missing here):
> 
> > Please note that Java 11 is required
> 
> This requirement does not seem fulfilled. Did you test it with Java 8?

You're right I missed that requirement (I didn't test it with Java8)

**Comment by frenck** [comment]
Did you test this at all?

**Comment by kilkenny44** [comment]
> Did you test this at all?

I test it locally on my home assistant instance, but I didn't realize that there are different packages for each arch (amd64 and aarch64) I will close tthat pull requests because of lack of testing the all build process. sorry

**Pull request closed without merging**
