### PR TITLE
⬆️ Upgrade UniFi Controller v6.0.41

### PR DESCRIPTION
**Pull request by lopesdasilva**
# Proposed Changes

Upgraded Controller to v6.0.41
Release notes:
https://community.ui.com/releases/UniFi-Network-Controller-6-0-41/25633411-0273-4197-bf30-4aff30b3701e

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Review by frenck — APPROVED** [review]

**Comment by frenck** [comment]
Thanks! 👍

**Comment by TheRealWaldo** [comment]
Any chance we can get a release of this?  Need to migrate from a controller that was already upgraded.

**Comment by TheRealWaldo** [comment]
@frenck ^

**Comment by frenck** [comment]
Not right now. Please do not ping me for that. It is kinda distracting. If you have questions, please use discord chat.

**Comment by Kamidh** [comment]
UniFi Network Controller 6.0.43
https://community.ui.com/releases/UniFi-Network-Controller-6-0-43/b28bb453-927a-4dd8-82f7-40af28505510

**Comment by frenck** [comment]
That is nice, but not related to this PR @Kamidh

**Pull request merged**
