### PR TITLE
Update UniFi Network Application to 6.4.54

### PR DESCRIPTION
**Pull request by marcomsousa**
# Proposed Changes

Update UniFi Network Application to 6.4.54

### CODE REVIEW

**Comment by marcomsousa** [comment]
This new version is stable for prod usage (reviewed by hostifi)

**Comment by per-oestergaard** [comment]
Hi. Great initiative. Was about to migrate from my existing server to this add-on. However, as I am running v6.4.54, I cannot import my settings. Anything the community can do helping bringing this forward?

**Comment by larsschwegmann** [comment]
Any updates on the missing labels?

**Comment by frenck** [comment]
image

This is a drive-by patch. The CI/CD didn't kick off either, and even if it did, the build would have failed because of dependencies.

While I appreciate the effort (including all people in this PR trying to push it forward), the fact it; the add-on build hasn't been tested before opening the PR.

Please, only open PRs if you actually can test something.

Thanks 👍

**Pull request closed without merging**
