### PR TITLE
⬆️ Upgrades UniFi Controller to 5.10.20

### PR DESCRIPTION
**Pull request by schliflo**

### CODE REVIEW

**Comment by stocker85** [comment]
This is still only a stable candidate?

**Comment by frenck** [comment]
@stocker85 No it is not.

**Comment by frenck** [comment]
image

**Comment by stocker85** [comment]
ah sorry I was stuck in the beta forum

**Comment by jcullen86** [comment]
Any chance of new release version so we can get his new version? Cheers

**Pull request merged**
