### PR TITLE
Pin binutils to 2.34-6ubuntu1.9

### PR DESCRIPTION
**Pull request by renewoensdregt**
# Proposed Changes

Pinning binutils from 2.34-6ubuntu1.8 to 2.34-6ubuntu1.9.

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Comment by cfergeau** [comment]
> # Proposed Changes
> 
> Pinning binutils to v1.9
> ## Related Issues
> 
> > ([Github link](https://help.github.com/articles/autolinked-references-and-urls/) to related issues or pull requests)

Nit: binutils is `v2.34`, and the package revision is `6ubuntu1.9`, there is not really a binutils `v1.9`

**Comment by frenck** [comment]
Obsolete, #491

**Comment by frenck** [comment]
Re-opening after reverting #491 in #497

**Review by frenck — APPROVED** [review]
Thanks, @renewoensdregt 👍 

../Frenck

**Pull request merged**
