### PR TITLE
Version update to 8.0.24

### PR DESCRIPTION
**Pull request by renewoensdregt**
Bumped version to 8.0.24

# Proposed Changes

> version bumped to 8.0.24

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Comment by renewoensdregt** [comment]
Not sure why it fails on binutils... it is the same dockerfile as the current main version where the same binutils version is being used...

**Comment by tjorim** [comment]
Did you even test this PR before opening it? E.g. run a docker build on your local system? The package was updated a few weeks ago. Please check the Ubuntu packages.

**Comment by renewoensdregt** [comment]
Thanks! No sorry and working on that now. I'm not an expert so learning as I go.  As the current main branch works, with all the same I expected it would work, but not. 

Will try to fix and run a build locally until I get it working. Any suggestions on how to find the right package version would be helpful.

**Comment by renewoensdregt** [comment]
Ok. fixed it. Now it compiles OK. Version was indeed changed, so now OK.
I see it only fails now for the labels, but I think I cannot update that. Last time Frenk updated those, so I hope it works now too.

**Comment by frenck** [comment]
I am few day out of office atm.

**Review by frenck — APPROVED** [review]
Thanks, @renewoensdregt 👍 

../Frenck

**Pull request merged**
