### PR TITLE
⬆️ Upgrades UniFi Network Application to 8.1.127

### PR DESCRIPTION
**Pull request by cwmoriarty**
Rel notes: https://community.ui.com/releases/UniFi-Network-Application-8-1-127/571d2218-216c-4769-a292-796cff379561

### CODE REVIEW

**Comment by andtsin** [comment]
Still no update... Why?

**Comment by cfergeau** [comment]
> Still no update... Why?

Because the maintainer of this add-on maintains a lot of other addons/integrations, and they need to have time available to merge this/release/...

**Review by frenck — APPROVED** [review]
Thanks, @cwmoriarty 👍 

../Frenck

**Comment by dyeadon** [comment]
Hi does this upgrade add SNMP functionality?

**Pull request merged**
